schemaVersion: '2.0.0'

metadataTest:
  exposedPorts: ["8080"]
  user: "nonroot"
  workdir: "/app"
  cmd: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]

fileExistenceTests:
  - name: 'Check for main.py'
    path: '/app/main.py'
    shouldExist: true
  - name: 'Check for requirements.txt'
    path: '/app/requirements.txt'
    shouldExist: true

commandTests:
  - name: "Check python version"
    command: "python"
    args: ["--version"]
    expectedOutput: ["Python 3.11.*"]

  - name: "API Health Check"
    command: "sh"
    args:
      - "-c"
      - |
        uvicorn main:app --host 0.0.0.0 --port 8080 &
        SERVER_PID=$!

        trap "kill $SERVER_PID 2>/dev/null" EXIT
        echo "Waiting for server to launch on port 8080..."
        for i in 1 2 3 4 5 6 7 8 9 10; do
          if nc -z localhost 8080; then
            echo "Server is up!"
            break
          fi
          sleep 1
        done

        echo "Performing health check..."
        curl -f http://localhost:8080/api
    expectedOutput:
      - "Welcome to our demo API"
