{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "assessment-api-service.fullname" . }}
  labels:
    {{- include "assessment-api-service.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "assessment-api-service.fullname" . }}
  labels:
    {{- include "assessment-api-service.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "assessment-api-service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "assessment-api-service.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
