{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "assessment-api-service.fullname" . }}-migrations"
  labels:
    {{- include "assessment-api-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      name: "{{ include "assessment-api-service.fullname" . }}-migrations"
      labels:
        {{- include "assessment-api-service.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: migrations-job
          image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}"
          imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
          command: {{ .Values.migrations.command | toYaml | nindent 12 }}
  backoffLimit: 1
{{- end }}
